[package]
# 排除不需要的文件或文件夹，以减小包大小
exclude = [
    "/target",        # 排除编译生成的文件夹
    "*.log",          # 排除日志文件
    "*.tmp",          # 排除临时文件
    "*.bak",          # 排除备份文件
    "large_files/",   # 替换为你项目中不需要的文件或文件夹
]
